---
# tasks file for /etc/ansible/roles/motd
- name: set motd
  become: yes
  template:
    src: /var/lib/jenkins/workspace/ansible-role-updates/roles/motd/files/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0444
